### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by yxm9264** [FaiChou/uCopy#1]

**Comment by yxm9264** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/50762364/205544201-f2a829b1-0e0c-40dd-99cc-b4a99ff59326.png">

**Comment by yxm9264** [comment]
抱歉，不是很懂SwiftUI，想拉下来学习下

**Comment by FaiChou** [comment]
需要安装一下第三方的库,  File - Add packages
搜索: LaunchAtLogin 和  KeyboardShortcuts 这两个库添加进去.
